name: CI Fuzz

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  FUZZING_SERVER_ADDRESS: 'app.code-intelligence.com:6773'
  WEB_APP_ADDRESS:  https://app.code-intelligence.com
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}



jobs:
  fuzz_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: sed "s/CI_FUZZ_API_TOKEN/${{ secrets.CI_FUZZ_API_TOKEN }}/g" webgoatWithAgentImage/start.sh && docker build webgoatWithAgentImage -t $IMAGE_NAME

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Deploy Docker image
            run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME --region europe-west1 --platform managed --ingress internal
      - id: start-fuzzing
        name: Build and Instrument
        uses: CodeIntelligenceTesting/github-actions/start-fuzzing@v3
        with:
          ci_fuzz_api_token: ${{ secrets.CI_FUZZ_API_TOKEN }}
          project: "projects/organizations_89d295318b3fded6_webgoat_git-95e1f92d"
          git_reference: ${{ github.sha }}
          fuzzing_server_address: ${{ env.FUZZING_SERVER_ADDRESS }}
      - id: monitor-fuzzing
        name: Fuzzing
        uses: CodeIntelligenceTesting/github-actions/monitor-fuzzing@v3
        with:
          ci_fuzz_api_token: ${{ secrets.CI_FUZZ_API_TOKEN }}
          test_collection_run: ${{ steps.start-fuzzing.outputs.test_collection_run }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_number: ${{ github.event.pull_request.number }}
          owner: ${{ github.event.repository.owner.login }}
          repository: ${{ github.event.repository.name }}
          fuzzing_server_address: ${{ env.FUZZING_SERVER_ADDRESS }}
          dashboard_address: ${{ env.WEB_APP_ADDRESS }}
      - id: report-coverage
        name: Report Coverage
        uses: CodeIntelligenceTesting/github-actions/report-coverage@v3
        if: ${{ github.event_name == 'pull_request' && (success() || failure()) }}
        with:
          ci_fuzz_api_token: ${{ secrets.CI_FUZZ_API_TOKEN }}
          test_collection_run: ${{ steps.start-fuzzing.outputs.test_collection_run }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_number: ${{ github.event.pull_request.number }}
          owner: ${{ github.event.repository.owner.login }}
          repository: ${{ github.event.repository.name }}
          git_reference: ${{ github.sha }}
          fuzzing_server_address: ${{ env.FUZZING_SERVER_ADDRESS }}
          dashboard_address: ${{ env.WEB_APP_ADDRESS }}
          
